stages:
  - deploy

deploy_production:
  stage: deploy
  tags:
    - runner-medium
  environment:
    name: production
    url: https://docs.hackerone.com
  image: node:11
  script:
    - echo "Deploy to production server"
    - yarn install
    - yarn deploy
  only:
  - master
