name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.DEPLOY_KEY }}
          deploy-branch: gh-pages
